[project]
name = "netset"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "notebook>=7.4.1",
    "pyqt6>=6.9.0",
    "pywin32>=310",
    "wmi>=1.5.1",
]
